hostname: switch1
domain_name: "lab.local"
loopback: 172.16.0.1
as: 65001
topology:
  - interface: Ethernet1
    lldp_neighbor: switch2
    lldp_neighbor_interface: Ethernet4
    ip: 10.10.10.0
    subnet: 31
    ebgp_peer_ip: 10.10.10.1
    ebgp_peer_loopback: 172.16.0.2 
    ebgp_peer_as: 65002
  - interface: Ethernet2
    lldp_neighbor: switch3
    lldp_neighbor_interface: Ethernet4
    ip: 10.10.10.2
    subnet: 31
    ebgp_peer_ip: 10.10.10.3
    ebgp_peer_loopback: 172.16.0.3  
    ebgp_peer_as: 65003
